### ISSUE TITLE
API Authentication: Query string credentials

### ISSUE THREAD

**Issue by adelawalla** [wso2-extensions/esb-connector-pardot#6]
**Description:**
Passing API credentials via query string will no longer be allowed as of March 27, 2019. Please update your API client as soon as possible. See the Request Format section of our API documentation for more details: http://developer.pardot.com/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Moved the issue to https://github.com/wso2/micro-integrator/issues/3485
